### ISSUE TITLE
How to generate nuscenes_infos_train_valid_mask_adjusted.pkl ?

### ISSUE THREAD

**Issue by wyz333www33ww** [BraveGroup/PointSAM-for-MixSup#4]
Thank you for your wonderful work! I've noticed that nuscenes_infos_train_valid_mask_adjusted.pkl is used in config files, and I would like to ask how to generate it. Looking forward to your reply

**Comment by YuxueYang1204** [comment]
Hi @wyz333www33ww ! We have updated the repo and support the OpenPCDet-based MixSup training on nuScenes.
